FROM nikolaik/python-nodejs:python3.11-nodejs16

ARG VUE_APP_UTC_OFFSET
COPY ./remrob-webapp /remrob-webapp

#RUN git clone https://github.com/unitartu-remrob/remrob-webapp.git \
WORKDIR /remrob-webapp
#RUN cd remrob-webapp \
RUN pip install --no-cache-dir -r requirements.txt \
	&& npm install \
	&& cp .env.production.example .env.production \
	&& npm run build

