version: '3.8'

services:
  vnc:
    image: robotont:base
    container_name: robo-1
    hostname: robo-1
    extra_hosts:
      - "robotont-6:192.168.88.6"
    environment:
      #- "ROS_MASTER_URI=http://robotont-7:11311"
      - ROS_MASTER=robotont-6 # Will be used to set master in ~/.bashrc
      - PASSWORD=remrob
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    cap_add:
    # Not required for initiation (tmpfs and cgroup enough, but there are some issues with running applications without SYS_ADMIN privileges)
      #- SYS_BOOT
      - SYS_ADMIN
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup
    # ports:
    #   - 5901:5901
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu, utility]
    networks:
      ros_net:
        ipv4_address: 192.168.88.192
networks:
  ros_net:
    external: true
    name: pub_net # - macvlan network
