- name: robo-1
  master_name: robotont-1
  self_ip: 192.168.200.101
  master_ip: 192.168.200.1
  ros_domain_id: 1
- name: robo-2
  master_name: robotont-2
  self_ip: 192.168.200.102
  master_ip: 192.168.200.2
  ros_domain_id: 2
- name: robo-3
  master_name: robotont-3
  self_ip: 192.168.200.103
  master_ip: 192.168.200.3
  ros_domain_id: 3
- name: robo-4
  master_name: robotont-4
  self_ip: 192.168.200.104
  master_ip: 192.168.200.4
  ros_domain_id: 4
- name: robo-5
  master_name: robotont-5
  self_ip: 192.168.200.105
  master_ip: 192.168.200.5
  ros_domain_id: 5
- name: robo-6
  master_name: robotont-6
  self_ip: 192.168.200.106
  master_ip: 192.168.200.6
  ros_domain_id: 6
- name: robo-7
  master_name: robotont-7
  self_ip: 192.168.200.107
  master_ip: 192.168.200.7
  ros_domain_id: 7
- name: robo-8
  master_name: robotont-8
  self_ip: 192.168.200.108
  master_ip: 192.168.200.8
  ros_domain_id: 8
- name: robo-9
  master_name: robotont-9
  self_ip: 192.168.200.109
  master_ip: 192.168.200.9
  ros_domain_id: 9
- name: robo-10
  master_name: robotont-10
  self_ip: 192.168.200.110
  master_ip: 192.168.200.10
  ros_domain_id: 10
- name: robo-11
  master_name: robotont-11
  self_ip: 192.168.200.111
  master_ip: 192.168.200.11
  ros_domain_id: 11
- name: robo-12
  master_name: robotont-12
  self_ip: 192.168.200.112
  master_ip: 192.168.200.12
  ros_domain_id: 12
- name: robo-13
  master_name: robotont-13
  self_ip: 192.168.200.113
  master_ip: 192.168.200.13
  ros_domain_id: 13
- name: robo-14
  master_name: robotont-14
  self_ip: 192.168.200.114
  master_ip: 192.168.200.14
  ros_domain_id: 14
- name: robo-15
  master_name: robotont-15
  self_ip: 192.168.200.115
  master_ip: 192.168.200.15
  ros_domain_id: 15
- name: robo-16
  master_name: robotont-16
  self_ip: 192.168.200.116
  master_ip: 192.168.200.16
  ros_domain_id: 16
- name: robo-17
  master_name: robotont-17
  self_ip: 192.168.200.117
  master_ip: 192.168.200.17
  ros_domain_id: 17
- name: robo-18
  master_name: robotont-18
  self_ip: 192.168.200.118
  master_ip: 192.168.200.18
  ros_domain_id: 18
- name: robo-19
  master_name: robotont-19
  self_ip: 192.168.200.119
  master_ip: 192.168.200.19
  ros_domain_id: 19
- name: robo-20
  master_name: robotont-20
  self_ip: 192.168.200.120
  master_ip: 192.168.200.20
  ros_domain_id: 20
- name: robo-21
  master_name: robotont-21
  self_ip: 192.168.200.121
  master_ip: 192.168.200.21
  ros_domain_id: 21
- name: robo-22
  master_name: robotont-22
  self_ip: 192.168.200.122
  master_ip: 192.168.200.22
  ros_domain_id: 22
- name: robo-23
  master_name: robotont-23
  self_ip: 192.168.200.123
  master_ip: 192.168.200.23
  ros_domain_id: 23
- name: robo-24
  master_name: robotont-24
  self_ip: 192.168.200.124
  master_ip: 192.168.200.24
  ros_domain_id: 24
- name: robo-25
  master_name: robotont-25
  self_ip: 192.168.200.125
  master_ip: 192.168.200.25
  ros_domain_id: 25
- name: robo-26
  master_name: robotont-26
  self_ip: 192.168.200.126
  master_ip: 192.168.200.26
  ros_domain_id: 26
- name: robo-27
  master_name: robotont-27
  self_ip: 192.168.200.127
  master_ip: 192.168.200.27
  ros_domain_id: 27
- name: robo-28
  master_name: robotont-28
  self_ip: 192.168.200.128
  master_ip: 192.168.200.28
  ros_domain_id: 28
- name: robo-29
  master_name: robotont-29
  self_ip: 192.168.200.129
  master_ip: 192.168.200.29
  ros_domain_id: 29
- name: robo-30
  master_name: robotont-30
  self_ip: 192.168.200.130
  master_ip: 192.168.200.30
  ros_domain_id: 30
- name: robo-31
  master_name: robotont-31
  self_ip: 192.168.200.131
  master_ip: 192.168.200.31
  ros_domain_id: 31
- name: robo-32
  master_name: robotont-32
  self_ip: 192.168.200.132
  master_ip: 192.168.200.32
  ros_domain_id: 32
- name: robo-33
  master_name: robotont-33
  self_ip: 192.168.200.133
  master_ip: 192.168.200.33
  ros_domain_id: 33
- name: robo-34
  master_name: robotont-34
  self_ip: 192.168.200.134
  master_ip: 192.168.200.34
  ros_domain_id: 34
- name: robo-35
  master_name: robotont-35
  self_ip: 192.168.200.135
  master_ip: 192.168.200.35
  ros_domain_id: 35
- name: robo-36
  master_name: robotont-36
  self_ip: 192.168.200.136
  master_ip: 192.168.200.36
  ros_domain_id: 36
- name: robo-37
  master_name: robotont-37
  self_ip: 192.168.200.137
  master_ip: 192.168.200.37
  ros_domain_id: 37
- name: robo-38
  master_name: robotont-38
  self_ip: 192.168.200.138
  master_ip: 192.168.200.38
  ros_domain_id: 38
- name: robo-39
  master_name: robotont-39
  self_ip: 192.168.200.139
  master_ip: 192.168.200.39
  ros_domain_id: 39
