# Automate everything from a single docker-compose template instead of having a separate one for each robot

- name: robo-1
  master-name: robotont-1
  self-ip: 192.168.88.192
  master-ip: 192.168.88.1
- name: robo-2
  master-name: robotont-2
  self-ip: 192.168.88.193
  master-ip: 192.168.88.2
- name: robo-3
  master-name: robotont-3
  self-ip: 192.168.88.194
  master-ip: 192.168.88.3
- name: robo-4
  master-name: robotont-4
  self-ip: 192.168.88.195
  master-ip: 192.168.88.4
- name: robo-5
  master-name: robotont-5
  self-ip: 192.168.88.196
  master-ip: 192.168.88.5
- name: robo-6
  master-name: robotont-6
  self-ip: 192.168.88.197
  master-ip: 192.168.88.6
- name: robo-7
  master-name: robotont-7
  self-ip: 192.168.88.198
  master-ip: 192.168.88.7
- name: robo-8
  master-name: robotont-8
  self-ip: 192.168.88.199
  master-ip: 192.168.88.8
