version: '3.8'

services:
  vnc:
    image: robotont:base
    container_name: robo-4
    hostname: robo-4
    extra_hosts:
      - "robotont-4:192.168.88.4"
    environment:
      - ROS_MASTER=robotont-4 # Will be used to set master in ~/.bashrc
      - PASSWORD=remrob # placeholder
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    cap_add:
      - SYS_BOOT
      - SYS_ADMIN
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu, utility]
    networks:
      ros_net:
        ipv4_address: 192.168.88.195
networks:
  ros_net:
    external: true
    name: pub_net # - macvlan network